### ISSUE TITLE
Add support for Enchants Squared or any "Illegal" enchant.

### ISSUE THREAD

**Issue by joex92** [alex55132/EnchantmentsExtractor#3]
Hi! 
I noticed that you added support for Enchantment Solutions.
Can you add suppor for [this one](https://www.spigotmc.org/resources/enchants-squared-custom-enchants-with-enchantment-table-villager-grindstone-and-anvil-support.86747/) too?

I was thinking that there are many custom enchants plugins and also the ability to enable "Illegal" enchants or not default vanilla-enchants' levels. So I was thinking that maybe would be better to add support for those too. There should be a way to do that.

**Comment by alex55132** [comment]
Hi @joex92 !

Unfortunately, EnchantmentsExtractor will discontinue Enchantment Solutions support in future updates since the plugin receives constant updates and I don't have the time to work on keeping it up to date.

About the illegal enchantments... The plugins is an enchantment extractor, so it supports disenchanting of almost all the enchanted vanilla items in the game.

There is not planning on adding enchanting feature in the near future.

Have a nice day!

**Comment by joex92** [comment]
but isn't enchantments like "Sharpness X" a vanilla enchant, just that is only obtainable with commands? not even those can be extracted? I'm just trying to understand how the enchanting code works, it should still work I believe (not yet worked on Minecraft api)

**Comment by alex55132** [comment]
Well, all depends on if the enchanted book can be enchanted with a higher level than V (Which is the max without commands) because the newly created book receives that level as exposed below @joex92 

Commands.java:53
`int level = entry.getValue();`

Commands.java:156
`EnchantmentStorageMeta enchantmentStorageMeta = (EnchantmentStorageMeta) meta;
enchantmentStorageMeta.addStoredEnchant(enchantment, level, false);`

**Comment by joex92** [comment]
hmm... so in theory, if I enable the possibility to enchant without commands higher than V with Essentials, should it work?

**Comment by alex55132** [comment]
I decided to try what would happen given that situation and the following occurs:

- The enchantment is NOT extracted, but it is removed from the item
- The transaction (Items or balance) is performed
- An empty enchanted book is given to the player

It's definitely not worth performing the disenchant on non-vanilla items @joex92

**Comment by joex92** [comment]
@alex55132 hmm ok... I understand... then what if you add a "failsafe"? when the item has non-vanilla enchants, it doesn't try to extract them but only the vanilla ones...

**Comment by alex55132** [comment]
@joex92 Tbh it would be a cool feature, can you please open another issue suggesting it? Lets keep this repo ordered :)

**Comment by joex92** [comment]
@alex55132 done #4
